
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:12 (PROJECT)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:12 (PROJECT)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2024/1/22 14:42:00。
      节点 1 上的项目“E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        d:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        d:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\3.27.4\\CompilerIdCXX\\.\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=d:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\3.27.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.49
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/3.27.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:12 (PROJECT)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2024/1/22 14:42:02。
      节点 1 上的项目“E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        d:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TC /analyze- /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        d:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\3.27.4\\CompilerIdC\\.\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=d:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.28
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/3.27.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:12 (PROJECT)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/CMakeScratch/TryCompile-9powlf"
      binary: "E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/CMakeScratch/TryCompile-9powlf"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/CMakeScratch/TryCompile-9powlf'
        
        Run Build Command(s): "d:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe" cmTC_7c396.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2024/1/22 14:42:04。
        节点 1 上的项目“E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-9powlf\\cmTC_7c396.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_7c396.dir\\Debug\\”。
          正在创建目录“E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-9powlf\\Debug\\”。
          正在创建目录“cmTC_7c396.dir\\Debug\\cmTC_7c396.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_7c396.dir\\Debug\\cmTC_7c396.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          d:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_7c396.dir\\Debug\\\\" /Fd"cmTC_7c396.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27051 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_7c396.dir\\Debug\\\\" /Fd"cmTC_7c396.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
          
        Link:
          d:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-9powlf\\Debug\\cmTC_7c396.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/CMakeScratch/TryCompile-9powlf/Debug/cmTC_7c396.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/CMakeScratch/TryCompile-9powlf/Debug/cmTC_7c396.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_7c396.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_7c396.vcxproj -> E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-9powlf\\Debug\\cmTC_7c396.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_7c396.dir\\Debug\\cmTC_7c396.tlog\\unsuccessfulbuild”。
          正在对“cmTC_7c396.dir\\Debug\\cmTC_7c396.tlog\\cmTC_7c396.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-9powlf\\cmTC_7c396.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.33
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:12 (PROJECT)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/CMakeScratch/TryCompile-0ewnar"
      binary: "E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/CMakeScratch/TryCompile-0ewnar"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/CMakeScratch/TryCompile-0ewnar'
        
        Run Build Command(s): "d:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe" cmTC_8a84a.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2024/1/22 14:42:06。
        节点 1 上的项目“E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-0ewnar\\cmTC_8a84a.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_8a84a.dir\\Debug\\”。
          正在创建目录“E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-0ewnar\\Debug\\”。
          正在创建目录“cmTC_8a84a.dir\\Debug\\cmTC_8a84a.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_8a84a.dir\\Debug\\cmTC_8a84a.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          d:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8a84a.dir\\Debug\\\\" /Fd"cmTC_8a84a.dir\\Debug\\vc141.pdb" /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27051 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8a84a.dir\\Debug\\\\" /Fd"cmTC_8a84a.dir\\Debug\\vc141.pdb" /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          
          CMakeCCompilerABI.c
        Link:
          d:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-0ewnar\\Debug\\cmTC_8a84a.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/CMakeScratch/TryCompile-0ewnar/Debug/cmTC_8a84a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/work/source/sdk_release/client_yssdk/x86-Debug/CMakeFiles/CMakeScratch/TryCompile-0ewnar/Debug/cmTC_8a84a.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_8a84a.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_8a84a.vcxproj -> E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-0ewnar\\Debug\\cmTC_8a84a.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_8a84a.dir\\Debug\\cmTC_8a84a.tlog\\unsuccessfulbuild”。
          正在对“cmTC_8a84a.dir\\Debug\\cmTC_8a84a.tlog\\cmTC_8a84a.lastbuildstate”执行 Touch 任务。
        已完成生成项目“E:\\work\\source\\sdk_release\\client_yssdk\\x86-Debug\\CMakeFiles\\CMakeScratch\\TryCompile-0ewnar\\cmTC_8a84a.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.23
        
      exitCode: 0
...
